# Generated by Django 3.0.3 on 2020-06-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200)),
                ('genre_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=200)),
                ('language_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_ISBN', models.CharField(max_length=200)),
                ('book_copies', models.PositiveIntegerField()),
                ('book_price', models.PositiveIntegerField()),
                ('book_description', models.CharField(max_length=200)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appERP.Author')),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appERP.Genre')),
                ('book_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appERP.Language')),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appERP.Publisher')),
            ],
        ),
    ]
