# Generated by Django 3.0.3 on 2020-06-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('l_email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('l_password', models.CharField(max_length=200)),
            ],
        ),
    ]
