# Generated by Django 3.0.3 on 2020-06-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0002_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_rollno', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=200)),
                ('student_phone_number', models.CharField(max_length=12)),
                ('student_DOB', models.CharField(max_length=200)),
                ('student_admissiondate', models.CharField(max_length=200)),
                ('student_address', models.CharField(max_length=200)),
                ('student_profile_pic', models.ImageField(blank=True, upload_to='pictures')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appERP.Course')),
            ],
        ),
    ]
