# Generated by Django 3.0.3 on 2020-06-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0004_auto_20200630_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='issue_student_name',
            new_name='issue_student_rollno',
        ),
    ]
