# Generated by Django 3.0.3 on 2020-07-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0005_auto_20200630_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='issue_book_name',
            new_name='issueBook_name',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='issue_student_rollno',
            new_name='issueRollno',
        ),
    ]
