# Generated by Django 3.0.3 on 2020-07-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0006_auto_20200702_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='issueBook_name',
            new_name='issueBookName',
        ),
    ]
