# Generated by Django 3.0.3 on 2020-07-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0008_remove_student_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='return_date',
        ),
    ]
