# Generated by Django 3.0.3 on 2020-07-04 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0009_remove_issuebook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
