# Generated by Django 3.0.3 on 2020-07-06 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0011_adminlogin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('l_email', models.EmailField(max_length=200)),
                ('l_password', models.CharField(max_length=200)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appERP.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
