# Generated by Django 3.0.3 on 2020-07-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0012_auto_20200706_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_login',
            name='l_email',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='name',
        ),
    ]
