# Generated by Django 3.0.3 on 2020-07-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0014_auto_20200706_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_login',
            old_name='rollno',
            new_name='l_rollno',
        ),
    ]
