# Generated by Django 3.0.3 on 2020-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0015_auto_20200706_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='fine',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
