# Generated by Django 3.0.3 on 2020-07-09 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0016_auto_20200709_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 7, 19, 5, 51, 33, 853413, tzinfo=utc)),
        ),
    ]
