# Generated by Django 3.0.3 on 2020-07-09 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appERP', '0018_auto_20200709_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='fine',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 6, 39, 46, 506022, tzinfo=utc)),
        ),
    ]
